Document: anxa-guard
Title: Debian anxa-guard Manual
Author: <insert document author here>
Abstract: This manual describes what anxa-guard is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/anxa-guard/anxa-guard.sgml.gz

Format: postscript
Files: /usr/share/doc/anxa-guard/anxa-guard.ps.gz

Format: text
Files: /usr/share/doc/anxa-guard/anxa-guard.text.gz

Format: HTML
Index: /usr/share/doc/anxa-guard/html/index.html
Files: /usr/share/doc/anxa-guard/html/*.html
