Document: amxa-guard
Title: Debian amxa-guard Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-guard is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-guard/amxa-guard.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-guard/amxa-guard.ps.gz

Format: text
Files: /usr/share/doc/amxa-guard/amxa-guard.text.gz

Format: HTML
Index: /usr/share/doc/amxa-guard/html/index.html
Files: /usr/share/doc/amxa-guard/html/*.html
